webots_driver:
  ros__parameters:
    left_encoder: left wheel sensor
    left_joint: left wheel motor
    right_encoder: right wheel sensor
    right_joint: right wheel motor
    robot_base_frame: base_link
    synchronization: false
    use_joint_state_publisher: true
    wheel_distance: 0.1054
    wheel_radius: 0.021
